apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: httptester-kaniko-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
    - name: dockerfile-path
      type: string
      default: Dockerfile
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: kaniko-build-and-push
      runAfter: [clone-repo]
      stepTemplate:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=/workspace/shared-workspace/$(params.dockerfile-path)
          - --context=/workspace/shared-workspace/
          - --destination=$(params.image-url)
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker
      workspaces:
        - name: source
          workspace: shared-workspace
  volumes:
    - name: docker-config
      secret:
        secretName: regcred
