namespace: httptester
deploymentName: tester

image:
  repository: wlanboy/http-tester
  tag: latest

service:
  port: 5000

ingress:
  # traefik | istio | none
  controller: istio
  hosts:
    - httptester.tp.lan
    - httptester.gmk.lan
    - httptester.big.lan
    - httptester.localhost

traefik:
  entryPoints:
    - web
    - websecure

istio:
  gateway:
    selector:
      istio: ingressgateway
