namespace: tester
deploymentName: tester

image:
  repository: wlanboy/http-tester
  tag: latest

service:
  port: 5000

ingress:
  enabled: true
  hosts:
    - httptester.tp.lan
    - httptester.gmk.lan
    - httptester.big.lan
